### ISSUE TITLE
LocalJumpError: no block given (yield) on lazy loading

### ISSUE THREAD

**Issue by hdamico** [nambrot/ar-find-in-batches-with-order#9]
Hello! I am having `LocalJumpError: no block given (yield)` whenever I want to use `find_in_batches_with_order` with lazy, for example `query.find_in_batches_with_order.lazy.each do |batch|`.
Is there a way to use lazy load?

**Comment by subelsky** [comment]
fyi this duplicates #7 so you may want to close this issue and chime-in on that issue
